name: Continous Integration
on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]
jobs:
  unit-functional-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: passer
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3

      - name: Install composer dependencies
        run: |
          composer update
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          cp .env.ci .env.test
          php artisan key:generate
          php artisan migrate:fresh --seed
      - name: Run Test
        run: php artisan test

      - name: Generate ide helper
        run: make helpers

      - name: Run Laravel Pint
        run: make pint

      - name: Run phpstan analyse
        run: make analyse
